### ISSUE TITLE
Markdown broken 

### ISSUE THREAD

**Issue by rodionos** [axibase/charts#78]
See [column] Settings in shared table, for example Label.
Find and fix similar markdown errors.

**Comment by rodionos** [comment]
https://github.com/axibase/charts/tree/master/widgets/shared-table#column-settings

**Comment by kghamilton89** [comment]
I've got a PR [here](https://github.com/axibase/charts/pull/79) open which corrects this and other grammar mistakes in Charts.

**Comment by kghamilton89** [comment]
New PR: https://github.com/axibase/charts/pull/80
